apiVersion:  v1
kind: Secret
metadata:
  name: aws-creds
type: Opaque
data:
  access_key_id: QUtJQVdOSUEzUERFSDZFTkRPNjM=
  secret_access_key: RVdYaG9uZGtIeVJBeUF4ZVlLRFZwRXJqQjhyMFBtc2VvZjhTcW53cQ==